### ISSUE TITLE
Check if expression text is different from "styled"

### ISSUE THREAD

**Issue by vmarcosp** [davesnx/styled-ppx#109]
Styled-ppx is not checking if expression txt is [%styled], e.g:

![Captura de Tela 2020-07-25 às 18 02 12](https://user-images.githubusercontent.com/20327229/88466970-365b4480-cea8-11ea-97ee-62acfd311451.png)

I tried using something like `[%graphql ...]` and it compiles. Taking a look at the code, i saw that there are no validations for that and the function that extracts the tag name from the text, returns "div" to anything that is not "styled":

```reason
let getTag = str => {
  switch (String.split_on_char('.', str)) {
  | ["styled"] => "div"
  | ["styled", tag] => tag
  | _ => "div"
  };
};
```
https://github.com/davesnx/styled-ppx/blob/master/src/styled_ppx.re#L50

**Comment by davesnx** [comment]
Hey @vmarcosp,

It looks like a silly bug regarding the ppx detection, shouldn't be too hard to fix.

Thanks for reporting.
