### ISSUE TITLE
CSS Support umbrella issue for 0.15

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#139]
Here is the umbrella of CSS properties that are broken in 0.15

```css
background: blue;
font-family: "Wonder Unit Sans", "sans-serif";
text-transform: uppercase;
line-height: 1.4; /* line-height: 100% works */
box-shadow: *;
grid-template-columns: repeat(auto-fill, minmax(200px, 1.0fr));
```

**Comment by rusty-key** [comment]
Not sure if it's a general issue or something that should be fixed for specific properties, but noticed this:
```ocaml
let gap = `px 20 

let entry = [%css {|
  grid-gap: $gap;
|}]
```
↓
```
  This has type:
    [> `px(int) ]
  But somewhere wanted:
    Css.Types.Length.t (defined as Css_AtomicTypes.Length.t)
```
(actually, it's a cryptic error now, but before that, I was getting something like this ^)

But in my case, inlining works:
```ocaml
(* compiles *)
let entry = [%css {|
  grid-gap: 20px;
|}]
```

**Comment by davesnx** [comment]
`width: calc(33% - 10px);`

**Comment by davesnx** [comment]
Added here https://github.com/davesnx/styled-ppx/issues/73

**Comment by davesnx** [comment]
All these properties are supported in nightlies and 0.21
