### ISSUE TITLE
Parser hangs in an infinite loop with property `grid-column-template`

### ISSUE THREAD

**Issue by rusty-key** [davesnx/styled-ppx#146]
Using `1.0.1-nightly.3badeeb.0`

After adding `grid-template-columns`, build hangs:
```
let counters = [%css {|
  display: grid;
  grid-template-columns: repeat(6, 100px);
|}]
```
Waited for a couple of minutes, but it didn't resolve into any error.

Killing the build, removing `grid-template-columns`, and rebuilding helped.

The value doesn't seem to matter, `grid-template-columns: 1fr 60px` results in the same issue

**Comment by EduardoRFS** [comment]
That is something that I saw before, is a parsing problem where it keeps stuck on an infinite loop
