### ISSUE TITLE
Syntax highlight for rescript files

### ISSUE THREAD

**Issue by AvroraPolnareff** [davesnx/styled-ppx#152]
Hi! I've started use vscode-styled-ppx extension for syntax highlight, but it doesn't seems to work with rescript files.
![image](https://user-images.githubusercontent.com/46288303/100544506-2e9d1980-3267-11eb-8129-71a3c3321e3c.png)
Can it be implemented in extension?

**Comment by davesnx** [comment]
Hey @AvroraPolnareff, we didn't implement support in `vscode-styled-ppx` for ReScript yet, it's on our list of things to do. 

I will keep this issue open to keep track if there's any progress. Thanks for opening it.

**Comment by davesnx** [comment]
Just published a new version (0.0.5) of the editor plugin for VSCode that have ReScript syntax highlight support. Hope you enjoy it, thanks for the request. Please open any issue regarding the syntax highlight

Thanks!
