### ISSUE TITLE
box-shadow type error

### ISSUE THREAD

**Issue by webican** [davesnx/styled-ppx#161]
Hi,

I can't get `box-shadow: 0 4px 6px rgba(0, 0, 0, 0.35);` to work with ReScript. Am I doing something wrong here?

```This has type: ('a, 'b, 'c, 'd)
Somewhere wanted:
  (
Emotion.Css.Length.t,
Emotion.Css.Length.t,
Emotion.Css.Length.t,
Emotion.Css.Length.t,
Emotion.Css.Color.t,
bool,
```

**Comment by davesnx** [comment]
Hey @webican, It's very possible that box-shadow isn't well supported in styled-ppx@0.15.0. We are working on the 1.0.0 version that will support all the CSS spec so box-shadow will be part of that.

I would suggest to use bs-emotion for those non supported properties like this one, meanwhile we improve the styled-ppx CSS parser.

Thanks for opening the issue, and it will remain open until we publish a 1.0.0.

**Comment by webican** [comment]
Hi @davesnx 

Thank you for a quick response! I'm really glad to see this project gets the attention it deserves - as much as I love rescript and emotion, I can't stand writing css as js. I want to have my cake and eat it too :)

**Comment by davesnx** [comment]
Thanks for the words, I believe we can deliver a really solid solution for it.

**Comment by davesnx** [comment]
Added in https://github.com/davesnx/styled-ppx/issues/139
