### ISSUE TITLE
Feature request: use array instead of list

### ISSUE THREAD

**Issue by webican** [davesnx/styled-ppx#162]
Please consider adding support for Arrays instead of Lists in the output. bs-css-emotion for example supports lists by opening from the Css module and arrays by opening from the CssJs module: [https://github.com/reasonml-labs/bs-css#usage-for-bs-css-emotion](https://github.com/reasonml-labs/bs-css#usage-for-bs-css-emotion)

**Comment by davesnx** [comment]
Oh sweet, yes I prefer arrays in this case.

Thanks for the idea @webican

**Comment by webican** [comment]
Awesome, thanks!
