### ISSUE TITLE
Is it possible to concatenate arrays using the array API?

### ISSUE THREAD

**Issue by persianturtle** [davesnx/styled-ppx#220]
I love the array API!

I'm guessing that arrays cannot be concatenated since that happens at runtime, and PPX happens before that.

That being said, is there any way to "combine" arrays? Consider:

```
type button = Primary | Secondary
module Button = %styled.button(
  (~variation=Primary) =>
    [
      %css("display: block"),
    ]->Js.Array2.concat(
      switch variation {
      | Primary => [%css("background-color: dodgerblue"), %css("color: white")]
      | Secondary => [%css("background-color: firebrick"), %css("color: blue")]
      },
    )
)
```

The above doesn't work since the `className` is rendered with a bunch of `[object Object]` strings.

The below works, but it's a bit tedious:

```
type button = Primary | Secondary
module Button = %styled.button(
  (~variation=Primary) =>
    [
      %css("display: block"),
      switch variation {
        | Primary => %css("background-color: dodgerblue")
        | Secondary => %css("background-color: firebrick")
      },
      switch variation {
        | Primary => %css("color: white")
        | Secondary => %css("color: blue")
      },
    ]
)
```

Keep up the great work!

**Comment by EduardoRFS** [comment]
That feels like a bug, the first one should definitely work from what I remember, but I don't think there is a test for it.

**Comment by davesnx** [comment]
Right, this isn't a bug as @EduardoRFS mentioned.

It's a current limitation of the implementation, right now `%css` does only the transformation of one  `Css.Rule` and I believe this should be fixed. 

The transformation does the following:

```
module Button = %styled.button(
  (~variation=Primary) =>
    [
      %css("display: block"),
      switch variation {
        | Primary => %css("background-color: dodgerblue")
        | Secondary => %css("background-color: firebrick")
      },
      switch variation {
        | Primary => %css("color: white")
        | Secondary => %css("color: blue")
      },
    ]
)

CssJs.style(. [|
	CssJs.css(display(`block)),
	switch variation {
      | Primary => CssJs.css(backgroundColor(`dodgerblue))
      | Secondary => CssJs.css(backgroundColor(`firebrick))
    }
|]);

Inside each switch statement, the type-checker expects one `Css.Rule.t` 
```

There's a possible workaround in bs-css with `CssJs.merge`: https://github.com/giraud/bs-css#merging-styles. If we change the entry-call to merge, it will change completely the css/cx meaning.

It's one of my biggest fears with the array API, so any idea/feedback would be very welcome!

As always, thanks for reporting @persianturtle

**Comment by davesnx** [comment]
As a possible workaround you can always do whatever you want inside the style call, such as:

```reason
module SequenceDynamicComponent = [%styled.div
  (~variation=Primary) => {
    let (background, color) = switch (variation) {
    | Primary => ([%css "background-color: dodgerblue"], [%css("color: white"])
    | Secondary => ([%css "background-color: firebrick"], [%css("color: blue"])
    };

  [|
    [%css "display: block;"]
    background,
    color,
  |]
  }
];
```

I will consider this an okay-ish way of solving the issue, since using the language is much better than re-inventing it. What are your thoughts @persianturtle?
