### ISSUE TITLE
Latest versions of `bs-css` & `bs-css-emotion` not working with `styled-ppx`

### ISSUE THREAD

**Issue by persianturtle** [davesnx/styled-ppx#229]
Nested styles like so:

```
module Header = %styled.header(`
  display: flex;
  align-items: center;
  height: 60px;
  border-bottom: 1px solid black;

  h1 {
    margin-left: 10px;
  }
`)
```

fail when using `"bs-css"`: `"^15"` and `"bs-css-emotion"`: `"^4"`. (Both `0.25.0` and `0.24.0` fail with the same compilation error).

It seems like the error is related to currying/uncurrying mismatches. 

`0.25.0` works fine when using `"bs-css"`: `"^14"` and `"bs-css-emotion"`: `"^3"`.

**Comment by davesnx** [comment]
That's an easy fix, bs-css 14 updated the interface for selectors being uncurried and the ppx generates them curried.

Thanks for the ping!

**Comment by davesnx** [comment]
Fixed https://github.com/davesnx/styled-ppx/pull/241#issuecomment-1000936985
