### ISSUE TITLE
Example in README.md not compiling

### ISSUE THREAD

**Issue by samtefey** [davesnx/styled-ppx#264]
Hi, thanks for putting together this library. I've tried the example below from the `README.md` 
```
module Link = %styled.a(
  (~color="#4299E1") => `
  font-size: 1.875rem;
  line-height: 1.5;
  text-decoration: none;
  margin: 0px;
  padding: 10px 0px;
  color: $(color);
`)
```
and get the following compiler error:
```
This has type: string
  Somewhere wanted:
    [<
  | #currentColor
  | #hex(string)
  | #hsl(
      Css_AtomicTypes.Angle.t,
      Css_AtomicTypes.Percentage.t,
      Css_AtomicTypes.Percentage.t,
    )
  | #hsla(
      Css_AtomicTypes.Angle.t,
      Css_AtomicTypes.Percentage.t,
      Css_AtomicTypes.Percentage.t,
      [#num(float) | #percent(float)],
    )
  | #rgb(int, int, int)
  | #rgba(int, int, int, [#num(float) | #percent(float)])
  | #transparent
  | #var(string)
  | #varDefault(string, string)
]
```
The above error show regardless of me mounting the `Link` component.

Thanks

**Comment by davesnx** [comment]
Hi, thanks for opening the issue!

This example points to an old version (0.21). Currently, bigger than 0.23 would require changing this snippet a bit. Treat the `~color` prop as a [bs-css](https://github.com/giraud/bs-css) color instead of a string.

This will be the equivalent

```
module Link = %styled.a(
  (~color=Css.hex("4299E1")) => `
  font-size: 1.875rem;
  line-height: 1.5;
  text-decoration: none;
  margin: 0px;
  padding: 10px 0px;
  color: $(color);
`)
```

**Comment by davesnx** [comment]
Pushed the fix into the README so fewer users will be confused by this!

https://github.com/davesnx/styled-ppx/commit/89915116f103a2ff9e952f61178118fbe40edb92

I will close this for now, but feel free to ask any question :D

**Comment by samtefey** [comment]
Thanks, really appreciated the quick response!
