### ISSUE TITLE
Allow an empty %css rule?

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#287]
I often find myself wanting to add some rules conditionally. Because I often use switch statement, (but it's true for ifs as well), all branches should have the same type. 
Because of that, I find myself with a need to add a property as a default value on the other side.

## Example

```rescript

let margin = (isLeft) =>
  switch isLeft {
  | true => %css("margin-left: 10px;")
  | false => %css("")
  }

module Component = %styled.div([
  %css("background-color: red;"),
  %css("border-radius: 20px;"),
  %css("box-sizing: border-box;"),
  margin(false),
])
```

`%css("")` is an invalid rule, since it's defined to not accept empty declarations.

In order to solve that I have 2 ideas:

1. Support empty declarations on `%css` extension
2. Create an %css.empty that transforms into an empty rule, such as `CssJs.unsafe("", "")`

---

## Conclusion

Not particularly fan of either, that's why I open the issue. Both have problems of discovery and aren't obvious.

**Comment by ashton** [comment]
Taking Styled Components as example, we could do something like:
```js
const Button = styled.button`
olor: ${props => props.$primary ? "white" : "#BF4F74"};
`;
```

since we don't have a concise ternary in Rescript could we have something like

```rescript
module Button = %styled.button([
  %css("background-color: red;"),
  %conditional(bool-evaluated-expression, "color: #BF4F74")
])
```

What do you think?

**Comment by davesnx** [comment]
Hi @ashton.

Thanks for the suggestion. I don't really like adding an extension (`%conditional`) that maps to a similar feature of the language (and if without an else). It needs documentation, a bit of AST transformation and it's hard to discover.

I would like to go into other directions. Maybe we should allow `%css("")` to be empty and create an empty Css.rule, but that seems rare as well.

**Comment by movepointsolutions** [comment]
I think option 2 (explicit %css.empty) is the way to go

**Comment by davesnx** [comment]
I would discourage to add a new feature for just conditionals, in styled-ppx safety matters a bit more than in styled-components, so I prefer to keep users to do:

```
let margin = (isLeft) =>
  switch isLeft {
  | true => %css("margin-left: 10px;")
  | false => %css("margin-left: 0px") // or margin-left: unset | none | etc..
  }

module Component = %styled.div([
  %css("background-color: red;"),
  %css("border-radius: 20px;"),
  %css("box-sizing: border-box;"),
  margin(false),
])
```
