### ISSUE TITLE
Fallback to `unsafe` on properties that bs-emotion doesn't support

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#31]
Would be amazing to keep a list of CSS properties that we can support without type-safeness with "unsafe" calls.

- [ ] Create a list of properties
- [ ] Make the mapping with those and output unsafe
- [ ] Add a warning
- [ ] Add a ppx config to enable/disable that warning

**Comment by EduardoRFS** [comment]
This also seems to be already implemented, as we're not using bs-emotion anymore and we actually use unsafe for valid but unknown properties
