### ISSUE TITLE
[Feature request] React Native support

### ISSUE THREAD

**Issue by davisuga** [davesnx/styled-ppx#310]
Emotion has an @emotion/native which has a very similar API, but with the basic React Native components. 
for example:
```js
import styled, { css } from '@emotion/native'

const Container = styled.View`
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 50px;
`

const Description = styled.Text({
  color: 'hotpink'
})

const Image = styled.Image`
  padding: 40px;
`

const emotionLogo = 'https://cdn.rawgit.com/emotion-js/emotion/main/emotion.png'
const App = () => (
      <Container
        style={css`
          border-radius: 10px;
        `}
      >
        <Description style={{ fontSize: 45, fontWeight: 'bold' }}>
          Emotion Primitives
        </Description>
        <Image
          source={{
            uri: emotionLogo,
            height: 150,
            width: 150
          }}
        />
      </Container>
    )
  }
}
```

The prop types can be safely copied from rescript react native. 
I am not very familiar with ppxes, but I would be able to contribute with, for example, documentation if needed.

**Comment by davesnx** [comment]
Hi @davisuga, Thanks for opening the issue :D

There are a few things that need to happen to support React Native in styled-ppx.

First, we should look into adding support on bs-css (1. adding the binding, 2. add properties that are supported only in native?) or maybe we could not use emotion out of the box and bind directly to inline styles: https://github.com/rescript-react-native/rescript-react-native/blob/main/src/apis/Style.res

Second, we could add all components from React Native as valid primitives on styled.xxx ppx.
