### ISSUE TITLE
[Feature request] JSX version 4

### ISSUE THREAD

**Issue by whitchapman** [davesnx/styled-ppx#327]
I use this ppx with Rescript, and the error message I get when attempting to use version 4 is:
```
  The record field children can't be found.

  If it's defined in another module or file, bring it into scope by:
  - Prefixing it with said module name: TheModule.children
  - Or specifying its type:
  let theValue: TheModule.theType = {children: VALUE}
```
Thanks!

**Comment by davesnx** [comment]
Hey, published a very alpha version of JSX4 support as `@davesnx/styled-ppx@0.35.1-7ef1e3d.0`.

It currently only supports JSX4, anything else will fail. I haven't test it in a real-project but made a few fixtures.

**Comment by davesnx** [comment]
Looking at the tests it seems like there's something broken with dynamic components with default values. If you encounter that, please share the snippet.

**Comment by davesnx** [comment]
Pushed a new version with most of the fixes, should be a little stable now.

```npm install @davesnx/styled-ppx@nightly```

A few things to take into account:

- It reads the `bs-config.json` and applies the JSX4 transformation to all styled components.
- It doesn't support reading the decorator `@@jsxVersion`. 
- It only does the "classic" method.

**Comment by davesnx** [comment]
I merged the PR with JSX4 support (v0.35), it's currently on beta and append here any issue you find with it.

**Comment by davesnx** [comment]
Ok, miss-typed the version and forgot to publish it. It's 0.36 and will be published in 10 minutes or so.

**Comment by whitchapman** [comment]
> Ok, miss-typed the version and forgot to publish it. It's 0.36. Can you try updating?

Yes, that did it. Outstanding!

**Comment by ashton** [comment]
Hello @davesnx! First let me thank you for being so quick and prestative! I don't know if I'm doing something wrong, but when I do: 

```rescript
module CardBody = %styled.div(`
  display: flex;
  justify-content: space-between;
`)

@react.component
let make = () => {
  <CardBody className="card-body">
     {"... many children here"}
  </CardBody>
}
```

Using the option at `bsconfig.json`: 

```json
{"jsx": {"version": 4, "mode": "classic"}}
```

It should render the `CardBody` component with the generated class name for the style that I provided using the `%styled` extension, and also concatenate it with the class name that I provide in the `className` argument right?

That is not what is happening: 
<img width="364" alt="image" src="https://user-images.githubusercontent.com/95974/231589223-c4a241e9-b5d8-4bbe-8d0e-17e3a7987696.png">
<img width="338" alt="image" src="https://user-images.githubusercontent.com/95974/231589262-650af729-e731-4b01-89c3-753cc1d1ebc7.png">

**Comment by ashton** [comment]
Heeey, any news?

**Comment by davesnx** [comment]
Pushed 0.38.1 fixing the className issue. Thanks for the testing!

**Comment by davesnx** [comment]
The missing piece on JSX4 is the new JSX transformation.

**Comment by davesnx** [comment]
Hey @ashton @whitchapman 

Do you have any OSS repository with ReScript that is using v11?

**Comment by ashton** [comment]
> Do you have any OSS repository with ReScript that is using v11?

Hey, I don't think v11 is out yet, but as soon as it gets released I'll update my projects with it

**Comment by davesnx** [comment]
Finishing the v11 support on https://github.com/davesnx/styled-ppx/issues/415

JSX4 should work nice
