### ISSUE TITLE
Issue with pre-build binary on Linux (0.36.2)

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#343]
Hey David, running 36.2 on circle ci  using cimage/node (ubuntu something)...im getting:

/home/circleci/noble/web/node_modules/@davesnx/styled-ppx/ppx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/circleci/noble/web/node_modules/@davesnx/styled-ppx/ppx)

/home/circleci/noble/web/node_modules/@davesnx/styled-ppx/ppx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/circleci/noble/web/node_modules/@davesnx/styled-ppx/ppx)

/home/circleci/noble/web/node_modules/@davesnx/styled-ppx/ppx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/circleci/noble/web/node_modules/@davesnx/styled-ppx/ppx)

any idea?

**Comment by davesnx** [comment]
Added ubuntu-20.04 in this PR: https://github.com/davesnx/styled-ppx/pull/341

When pre-building the binary with ubuntu-latest is expected to have glib 2.35/34/33 while our system (the same as yours I believe) uses 2.31. This is in fact an issue for pre-building binaries and pushing them to npm and the fact we build them without being linked.

Reading a bit more about how we could link them statically I found this resource: https://ocamlpro.com/blog/2021_09_02_generating_static_and_portable_executables_with_ocaml/

**Comment by AlexMoutonNoble** [comment]
Thanks dave. I tried the nightly and it works here.

**Comment by davesnx** [comment]
That's awesome. I will close it when it lands as stable!
