### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#37]

**Comment by vmarcosp** [comment]
@davesnx do you need help? I can help with this... I created [reform's logo](https://github.com/Astrocoders/reform/issues/158) and if u want, can check my porfolio [here](https://dribbble.com/vmarcosp) :)

**Comment by davesnx** [comment]
Hey @vmarcosp, I currently have a plan for the logo which will happen at some point. 

Thank you very much for your suggestion, I do love reforms logo and your portfolio a lot. I will let you know if the plan goes away.

Thanks for the interest

**Comment by vmarcosp** [comment]
@davesnx ahh great! No problem! If you need any help with something like this, you can count on me :)
