### ISSUE TITLE
Bug with rescript compilation

### ISSUE THREAD

**Issue by ashton** [davesnx/styled-ppx#397]
Hey! I've installed `"@davesnx/styled-ppx": "^0.50.0",` and when trying to run my project using rescript (10.1.4) with rescript-react (0.11.0), it shows the following error
![image](https://github.com/davesnx/styled-ppx/assets/95974/e8abdb03-eda5-4e44-a053-43c82d2f026f)

It seems that the compilation of [this line](https://github.com/davesnx/styled-ppx/blob/b06c03a8af9c6976cd1c653e9d96dfaad6d0e976/packages/css/native/shared/Css_AtomicTypes.ml#L2249) is generating triple quotes and thus, an invalid syntax in the `.bs.js` file.
![Cursor_and_less](https://github.com/davesnx/styled-ppx/assets/95974/4b582e01-3c6e-47fe-83ee-4b5fb0facae5)

**Comment by lubegasimon** [comment]
In the meantime, those can be fixed by manually escaping the quotes/

**Comment by ashton** [comment]
Which quotes exactly? (version 0.40.1 is working perfectly)

**Comment by lubegasimon** [comment]
> Which quotes exactly? (version 0.40.1 is working perfectly)

For example; `case """ :` to `case "\"":`

**Comment by lubegasimon** [comment]
>  (version 0.40.1 is working perfectly)

We shall investigate and fix what could be causing the regression. Thanks for the report

**Comment by ashton** [comment]
> For example; `case """:` to `case "\"":`
but those are generated files, everytime I run a `npm install` this would be overwritten

**Comment by ashton** [comment]
Also, not sure if it's related, but the PPX itself is not being recognized by rescript:
![image](https://github.com/davesnx/styled-ppx/assets/95974/ca7719ec-7632-4f6b-8b87-fa58fd49fb3a)

@lubegasimon Do you want me to open another issue?

**Comment by lubegasimon** [comment]
> Also, not sure if it's related, but the PPX itself is not being recognized by rescript: ![image](https://private-user-images.githubusercontent.com/95974/289390330-ca7719ec-7632-4f6b-8b87-fa58fd49fb3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDcxMTksIm5iZiI6MTcwMjI0NjgxOSwicGF0aCI6Ii85NTk3NC8yODkzOTAzMzAtY2E3NzE5ZWMtNzYzMi00ZjZiLThiODctZmE1OGZkNDlmYjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDIyMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmN2E1M2YwMTYwNGFhYWY1OWYzNGVjMzlkNTc4ZjNlMWFiNzQxNmFiMmRkZGJkYzJmNDgyYjY4YTllMThkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGEPuLWULxhtfzv4dwWGVfkpSjrhiPn5QWkxx8OkKSw)
> 
> @lubegasimon Do you want me to open another issue?

Yes, though it seems something is missing out during the installation. Does this -- https://styled-ppx.vercel.app/getting-started guide help?

**Comment by ashton** [comment]
created #398 to check the issue with PPX

**Comment by lubegasimon** [comment]
> It seems that the compilation of [this line](https://github.com/davesnx/styled-ppx/blob

No, one occurrence is at https://github.com/davesnx/styled-ppx/blob/b06c03a8af9c6976cd1c653e9d96dfaad6d0e976/packages/css/native/shared/Css_AtomicTypes.ml#L2281

**Comment by davesnx** [comment]
I believe the issue has been fixed in main, but didn't release a npm package yet. Let me try to reproduce and double-check ReScript and release a 0.51

**Comment by davesnx** [comment]
Updated the https://github.com/davesnx/try-styled-ppx repository with ReScript 10 and styled-ppx 0.53 working nicely
