### ISSUE TITLE
Support @container

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#422]
https://developer.mozilla.org/en-US/docs/Web/CSS/@container

After https://github.com/davesnx/styled-ppx/issues/357 we can implement container queries with same parsing rules

**Comment by johnhaley81** [comment]
In lieu of this being supported, is there a way to inject a raw CSS string bypassing the parsing?

**Comment by davesnx** [comment]
There's no mechanism of bypassing the CSS parser, mostly because it would be difficult to design in menhir. That being said, AFAIK @container is easy to implement

**Comment by endlo** [comment]
I could also use this - just ran into some weird styling with media queries on a component that are only there due to how it gets sized on the parent under certain widths, making it more difficult to share in places that have different behavior 😭

**Comment by zakybilfagih** [comment]
Supported #476 since v0.58.0
