### ISSUE TITLE
Support [%styled] and [%styled ""]

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#45]
Appears a weird error on the CSS_Parse apparently:

`Parse error while reading token 'EOF'`

Not entirely sure that it's the Parser itself, If you run Css_parse with an empty string works fine, maybe is the ppx detection that doesn't make it correctly.

**Comment by dylanirlbeck** [comment]
@davesnx I've also been seeing this issue using the parser sometimes --- I'll let you know if I'm able to identify a fix.

**Comment by dylanirlbeck** [comment]
@davesnx Did this issue get fixed in https://github.com/davesnx/styled-ppx/pull/81? If so, perhaps we should consider opening a PR against `ocaml-css-parser` for this change:

**Comment by davesnx** [comment]
It's fixed ye. I will open a PR soon!
