### ISSUE TITLE
string_of_dimensions is missing a space on native

### ISSUE THREAD

**Issue by purefunctor** [davesnx/styled-ppx#474]
Native:
https://github.com/davesnx/styled-ppx/blob/0f3e805cf05734ad9223952c42c22eae4101911c/packages/css/native/Css_Js_Core.ml#L1679-L1680

JS:
https://github.com/davesnx/styled-ppx/blob/0f3e805cf05734ad9223952c42c22eae4101911c/packages/css/js/Css_Js_Core.ml#L1728-L1731

**Comment by davesnx** [comment]
Fixed in main. Thanks for reporting @purefunctor
