### ISSUE TITLE
Add `print-color-adjust` declaration

### ISSUE THREAD

**Issue by johnhaley81** [davesnx/styled-ppx#519]
👋 

I'm working on a feature that requires the background colors of divs to show up during printing and I can add `-webkit-print-color-adjust` declarations but the non-webkit version doesn't compile:

![image](https://github.com/user-attachments/assets/6fe41f2f-93e4-46b8-8398-e84fba937ffe)

**Comment by davesnx** [comment]
I asume using `print-color-adjust` alone isn't sufficient?

**Comment by johnhaley81** [comment]
So I just tested this in FF/Safari/Chrome on OSX and `print-color-adjust: exact` without the vendor prefix works on all of them so that might be sufficient. I have not tested this on windows/linux however.

**Comment by davesnx** [comment]
Sounds good. Autoprefixing works by emotion at client runtime (and if SSR by us), this will be done by us in the future as well (when we remove emotion).

No need to parse -webkit- and other prefixed properties from our parser. Closing this!
