### ISSUE TITLE
Error While Running Demo

### ISSUE THREAD

**Issue by idkjs** [davesnx/styled-ppx#52]
Hi @davesnx. Thanks for sharing this work.

I am trying to run the demo unsuccessfully.

I have cloned the demo from this repo and followed the steps from the readme after running it out of the box did not work.

Here is the reproduction: https://github.com/idkjs/styled-ppx-master-demo

I have run `yarn global add @davesnx/styled-ppx @ahrefs/bs-emotion` and added `"ppx-flags": ["@davesnx/styled-ppx/styled-ppx", "@ahrefs/bs-emotion"]` to [`bsconfig.json`](https://github.com/idkjs/styled-ppx-master-demo/blob/4bf22feeb919cdac4b4b9e4c28ee6cee731f1b73/bsconfig.json#L17).

Upon running `yarn run re:watch` I get the following compiler error which I am not able to resolve:

```sh
➜  styled-ppx-master-demo [master]yarn run re:watch
yarn run v1.22.0
warning package.json: No license field
$ bsb -make-world -w
bsb: no work to do.
bsb: no work to do.
bsb: no work to do.
>>>> Start compiling 
[1/3] Building src/index.reast
FAILED: src/index.reast 
/Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/bs-platform/lib/bsc.exe  -w -30-40+6+7+27+32..39+44+45+101 -color always -bs-jsx 3 -ppx /Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/@davesnx/styled-ppx/styled-ppx -ppx /Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/@ahrefs/bs-emotion  -o src/index.reast -bs-syntax-only -bs-binary-ast /Users/prisc_000/Downloads/styled-ppx-master-demo/src/index.re
sh: /Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/@ahrefs/bs-emotion: is a directory

  We've found a bug for you!
  /Users/prisc_000/Downloads/styled-ppx-master-demo/src/index.re
  
  Error while running external preprocessor
Command line: /Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/@ahrefs/bs-emotion '/var/folders/dz/xzttny_14gs2lgxcvl5lm5680000gn/T/camlppx947ec0' '/var/folders/dz/xzttny_14gs2lgxcvl5lm5680000gn/T/camlppx74f477'

  
FAILED: subcommand failed.
>>>> Finish compiling(exit: 1)

```

Any guidance would be appreciated. Thank you.

**Comment by idkjs** [comment]
If I add `yarn add --dev @ahrefs/bs-emotion-ppx` per the ahrefs/bs-emotion readme at [bs-emotion-ppx](https://github.com/ahrefs/bs-emotion#bs-emotion-ppx) and change `bsconfig.json`'s `ppx-flag` to 

```json
  "ppx-flags": ["@davesnx/styled-ppx/styled-ppx", "@ahrefs/bs-emotion-ppx/bin/bs-emotion-ppx"],
```

I get the following compiler error: 

```sh
➜  styled-ppx-master-demo [master*]yarn run re:watch                    
yarn run v1.22.0
warning package.json: No license field
$ bsb -make-world -w
[37/37] Building src/ReactDOMRe.cmj
[5/5] Building src/Css.cmj
[8/8] Building src/Emotion.cmj
>>>> Start compiling 
[2/4] Building src/index.reast
FAILED: src/index.reast 
/Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/bs-platform/lib/bsc.exe  -w -30-40+6+7+27+32..39+44+45+101 -color always -bs-jsx 3 -ppx /Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/@davesnx/styled-ppx/styled-ppx -ppx /Users/prisc_000/Downloads/styled-ppx-master-demo/node_modules/@ahrefs/bs-emotion-ppx/bin/bs-emotion-ppx  -o src/index.reast -bs-syntax-only -bs-binary-ast /Users/prisc_000/Downloads/styled-ppx-master-demo/src/index.re

  We've found a bug for you!
  /Users/prisc_000/Downloads/styled-ppx-master-demo/src/index.re 12:45
  
  10 │   font-size: 30px;
  11 │ |}];
  12 │ module Component = [%styled {| margin-left: -10px |}];
  13 │ module Link = [%styled.a {| color: #454545 |}];
  14 │ 
  
  Unsupported delimiter
  
FAILED: subcommand failed.
>>>> Finish compiling(exit: 1)

```

So it looks like maybe that is going in the right direction but it still isn't compiling. Thanks again

**Comment by davesnx** [comment]
Hey @idkjs,

Thanks for opening the issue, I created a demo that works successfully: https://github.com/davesnx/try-styled-ppx

It's not needed to add bs-emotion-ppx as a ppx here.  

I pushed the demo with an unsupported feature, negative numbers: `module Component = [%styled {| margin-left: -10px |}];`. I already fixed that in master.

**Comment by idkjs** [comment]
Thanks for working demo and note on negative numbers. Will watch the other issue for updates. Peace to you.

**Comment by davesnx** [comment]
Thanks to you, I did a few improvements to the docs!

Let me know in discord, Thanks!

**Comment by idkjs** [comment]
Glad to help!
