### ISSUE TITLE
Error Running Test

### ISSUE THREAD

**Issue by idkjs** [davesnx/styled-ppx#53]
I have forked and run this repo. Built with `esy` command and then attempted to run `esy test`.

I got the following output in the terminal regarding the `dune` version:

```sh

➜  styled-ppx [master]esy test
File "/Users/prisc_000/.opam/ocaml-base-compiler.4.08.1/lib/js_of_ocaml-compiler/dune-package", line 1, characters 11-14:
1 | (lang dune 2.2)
               ^^^
Error: Version 2.2 of dune is not supported.
Supported versions:
- 0.0
- 1.0 to 1.11
➜  styled-ppx [master]
```

Is this expected or did i do something wrong?

Thanks.

**Comment by davesnx** [comment]
I'm not using dune 2.2, I'm using 1.11. 

Tried with 2 but I didn't got those tests working
