### ISSUE TITLE
minmax doesn't seem to work with grid-template-columns

### ISSUE THREAD

**Issue by phated** [davesnx/styled-ppx#73]
I tried using this snippet and it seems to be failing:

```reasonml
module Container = [%styled.div
    {|
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1.0fr));
    grid-gap: 1rem;
    padding: 0.5rem;
  |}
];
```

The issue seems to be `minmax` but I'm not sure what exactly.

An aside: common usage of `fr` unit is `1fr` so it would be cool to convert an int to a float before passing to bs-emotion. Not sure how hard that is.

**Comment by davesnx** [comment]
Hey @phated 

Some CSS features are fully implemented, but It's just a matter to bridge them to bs-emotion.

I will take a look at this one and try to get full support. I will re-name this issue to keep track of the status and let you know.

Thanks for opening the issue.

**Comment by davesnx** [comment]
Hey @phated, the issue comes from `repeat`, usually, the css functions only accept a list of arguments or one argument, in this case receives 2 arguments where the second is a list! 

So, the bridge between AST and emotion was generating:
```
let styles = Emotion.(
  css(
    [
     gridTemplateColumns(
       list(
         [
           repeat(
               autoFill(
					[minmax((px(200), px(10)))]
				)
              )
         ]
        )
      )
    ]
  )
);
```
instead of 
```
let styles = Emotion.(
  css(
    [
     gridTemplateColumns(
       list(
         [
           repeat(
             (
               autoFill,
               [minmax((px(200), px(10)))]
              )
            )
         ]
        )
      )
    ]
  )
);
```

I will be able to fix it asap, sorry for the late response!

**Comment by davesnx** [comment]
This is related with https://github.com/davesnx/styled-ppx/issues/47
