### ISSUE TITLE
Support variables in one of the values

### ISSUE THREAD

**Issue by davesnx** [davesnx/styled-ppx#74]
Currently this works, since we transform any reason variable css to unsafe emotion calls: 
```
let space = "10px";

<div className=[%css {|
	margin: $space;
|}] />
```

but then, this doesn't. Since we needed to transform the entire thing to unsafe, this is currently not implemented.
```
let space = "10px";

<div className=[%css {|
	margin: 10px $space;
|}] />
```

**Comment by rusty-key** [comment]
I am not sure it's related, but it doesn't work for me when combining values with units too:
```ml
let size = 20

let fontSize = [%css {|
  font-size: $(size)px;
|}]
```
↓↓
```
  14 │ let fontSize = [%css {|
  15 │  font-size: $(size)px;
  16 │ |}]
  
  This has type:
    string
  But somewhere wanted:
    int
```

**Comment by davesnx** [comment]
Hey @rusty-key,

Right now, we only support string interpolation, so without specifying the type as here:

```reason
let size = "20px";

let fontSize = [%css {|
  font-size: $size;
|}];
```

We are rethinking the casting with the same syntax as you exposed. Since we need to make things a little complex to guess which types are valid without accessing the typed tree.

Thanks for opening the issue.

**Comment by davesnx** [comment]
Nightly version supports this, will be enabled in main soon.
